version: 2

jobs:
  build:
    docker:
      - image: circleci/node:10

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "package.json" }}
            - dependency-cache-

      - run: npm install

      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules

      - run: npm run update -- --summoner Avol9 && npm run update -- --summoner skyfall3665
      - run: npm run update:netlify
workflows:
  version: 2

  test:
    jobs:
      - build

  nightly:
    triggers:
      - schedule:
          # 14 for 8am cst during DST, 13 otherwise.
          cron: '0 13 * * *'
          filters:
            branches:
              only:
                - master
    jobs:
      - build
